In [2]:
import numpy as np

In [26]:
#function declaration includiing ValueError

def calculate(x):
    if len(x) !=9:
        raise ValueError('List must contain nine numbers.')
    
#convert to numpy array
    x=np.array(x)
    x=x.reshape(3,3)

#testing output
    print(x)

#return of calculator
    return {
    'mean': [x.mean(axis=0).tolist(), x.mean(axis=1).tolist(), np.mean(x).tolist()],
    'variance': [x.var(axis=0).tolist(), x.var(axis=1).tolist(), np.var(x).tolist()],
    'standard deviation': [x.std(axis=0).tolist(), x.std(axis=1).tolist(), np.std(x).tolist()],
    'max': [x.max(axis=0).tolist(), x.max(axis=1).tolist(), np.max(x).tolist()],
    'min': [x.min(axis=0).tolist(), x.min(axis=1).tolist(), np.min(x).tolist()],
    'sum': [x.sum(axis=0).tolist(), x.sum(axis=1).tolist(), np.sum(x).tolist()]
};

In [27]:
#test
calculate([0,1,2,3,4,5,6,7,8])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}